### ISSUE TITLE
Ricoh MP-C4503 PDF/PS/PXL provided ppds do not work but Gutenprint PPD works

### ISSUE THREAD

**Issue by malsaqer** [OpenPrinting/libcupsfilters#33]
**Describe the bug**
I have a Ricoh MP-C4503 copier and using the cups provided Gutenprint ppd file with no issue but it does not provide utilization of options like the attached finisher.

If I change the PPD file to the Ricoh provided ones located in openprinting then cups do send the job, and the printer shows a Job processing then cancelled with error like "The job was reset".

I tried by removing the printer and readd from scratch as well as just changing the driver from the working Gutenprint ppd file to the Ricoh provided file but get the same result.

**To Reproduce**
1. Add the printer using any printer manager program.
2. Follow instructions (either add a discovered network printer or add the printer's ip address directly)
3. When choosing the driver, I choose the Ricoh PPD driver downloaded from openprinting.org
4. Try to print a file or a click on "print test page"
5. Cups show job completed
6. Printer shows "the Job was resest"

**Expected behavior**
The printer prints.

**System Information:**
 - Fedora 38 64bit
 - Using any pdf viewer or print directly from command line
 - CUPS version:  2.4.6

**Comment by tillkamppeter** [comment]
For me all the generated PostScript files look OK and they display correctly with evince (which uses Ghostscript). So I am not able to locate any bug. Looks like the PPD provided by Ricoh perhaps supplies some incompatible or broken PostScript code with one of the options. As @malsaqer does not have the printer any more and will not necessarily get the same model as replacement I will close this bug here, and generally, if a printer supports other formats than PostScript, recommend using one of the other formats, as printer's PostScript interpreters are often buggy. Especially we see here that the printer in question works as a PDF or PXL printer.

**Comment by malsaqer** [comment]
> For me all the generated PostScript files look OK and they display correctly with evince (which uses Ghostscript). So I am not able to locate any bug. Looks like the PPD provided by Ricoh perhaps supplies some incompatible or broken PostScript code with one of the options. As @malsaqer does not have the printer any more and will not necessarily get the same model as replacement I will close this bug here, and generally, if a printer supports other formats than PostScript, recommend using one of the other formats, as printer's PostScript interpreters are often buggy. Especially we see here that the printer in question works as a PDF or PXL printer.

We replaced the printer with ricoh MP-C3504 which works just fine using either PS or PDF providing PPD drivers!  Thank you for providing help with the previous printer with a fix that made it work until replaced.

**Comment by tillkamppeter** [comment]
Thanks for the update, @malsaqer !
